export const halloweenPatchworkStyle = {
  name: "halloweenPatchwork",
  displayName: "Halloween",
  description: "Family-friendly spooky Frankenstein-inspired 3D cartoon style",

  characterStyle: "Characters are creatures stitched together from different animal parts. Each character is visibly assembled from mismatched pieces: a cat's head sewn to a rabbit's body, a bird's wings attached to a dog's torso, or a mouse's tail connected to a bear's form. Bodies show clear, thick black stitches holding different colored sections together, with visible thread ends and uneven seams. Each body part has distinct textures and colors - some parts are furry, others are smooth fabric, creating a mismatched appearance. Some parts have small fabric patches sewn on like repairs. Eyes: glowing green orbs without pupils, bright and expressive, emitting eerie unnatural light. Mouths: crooked smiles with stitches or missing teeth, sometimes showing a mischievous grin. Characters have a textured appearance with visible stitching details and some parts feature red accessories (bow ties, scarves) for contrast. The overall look is playful yet eerie, like animated stitched toys in a Halloween world with a horror-comedy aesthetic.",

  environmentStyle: "Spooky but fun Halloween backdrops in 3D: glowing pumpkins with carved faces, crooked trees silhouetted against dark sky, haunted houses with warm lights, full moon and light fog. Atmosphere is playful, not scary — closer to a family Halloween special. Add cartoon bats with glowing green eyes, flickering lanterns, or smiling jack-o'-lanterns for extra charm. Background features misty forest scenes with bare trees and dimly lit environments.",

  colorPalette: "Primary colors: muted greens, bluish greys, soft blacks, dark fabric tones. Accent colors: glowing green (eyes), pumpkin orange, neon purple, bright red for accessories. Backgrounds: midnight blue, foggy teal, violet, dark silhouettes. Strong contrast between muted bodies and glowing details. The green eyes provide stark contrast against dark surroundings.",

  renderStyle: "High-quality 3D animation, Pixar-like smooth surfaces with Tim Burton/Coraline atmosphere. Rounded proportions (big head, short limbs) with clear fabric seams, stitches, and patches. Glowing eyes as the main light source, casting faint green glow on surroundings. Soft dramatic lighting with moonlight + pumpkin glow. Movements slightly puppet-like but bouncy and playful. Textures are detailed but not realistic, giving a playful, exaggerated feel with handcrafted quality."
};